# Importando as Bobliotecas 

In [1]:
import pandas as pd
import os

In [36]:
arquivos = os.listdir()

licitacao = pd.read_excel('Empresa A.xlsx')

licitacao = licitacao.rename(columns={'Total' : 'Empresa A'})

licitacao = licitacao.drop(['Valor Unitário'], axis=1)
#display(licitacao)

empresas = arquivos[18:25]
#print(empresas)
for empresa in empresas:
 proposta = pd.read_excel(empresa)
 licitacao[empresa[:-5]] = proposta['Total'].copy()
display(licitacao)

Item Descrição do Item  Quantidade  Empresa A  Empresa B  Empresa C  \
0       1            Item 1          50       2350       1250       1450   
1       2            Item 2          96       2688       1632       2496   
2       3            Item 3          58       1566        754       1276   
3       4            Item 4          69       1863        828       3450   
4       5            Item 5          61       1342       1281       1708   
..    ...               ...         ...        ...        ...        ...   
195   196          Item 196          60       1440       1440       1020   
196   197          Item 197          82       2050       1066       3116   
197   198          Item 198         100       3400       2000       1100   
198   199          Item 199          67        804       1072       2680   
199   200          Item 200          59       1180       1357       1121   

     Empresa D  Empresa E  Empresa F  Empresa G  Empresa H  
0         2100       2050       1000        650       2450  
1         2208       1248       2592       1440       1056  
2         1914       1508       2146       2378       1508  
3          759       1932       2208       1725       3105  
4         1769       2684       1830       2318        610  
..         ...        ...        ...        ...        ...  
195       2400       1620       2100       2160       2580  
196       1886       1394       3608       3608       1804  
197       1000       3300       4900       1100       1100  
198       1809       2814       2881        670       3015  
199       1357       1711       2419       2065        767  

[200 rows x 11 columns]

# Verificando Valores Totais

In [34]:
for coluna in licitacao.columns[3:]:
   total = licitacao[coluna].sum()
   print(f'{coluna} : R$ {total:,.2f}')

Empresa A : R$ 429,316.00
Empresa B : R$ 267,971.00
Empresa C : R$ 447,536.00
Empresa D : R$ 421,243.00
Empresa E : R$ 446,904.00
Empresa F : R$ 472,515.00
Empresa G : R$ 428,703.00
Empresa H : R$ 459,468.00


# Análise inicial e possíveis ações: 


1. **Empresa F** tem o maior total de R$ 472,515.00, indicando que é a que recebeu mais recursos financeiros na licitação.
   
2. **Empresa B** possui um total significativo de R$ 267,971.00, que é consideravelmente menor que o da Empresa F, mas ainda substancial.

3. **Empresas C, E, H** também têm valores elevados, todos acima de R$ 400,000.00, sugerindo que também são beneficiadas com quantias consideráveis.

### Possíveis Ações:

- **Análise de Desempenho e Eficiência:** Avaliar se os montantes recebidos estão alinhados com o desempenho e a eficiência das empresas. Empresas que recebem mais recursos devem ser monitoradas de perto para garantir que estão cumprindo com os requisitos contratuais e oferecendo um bom retorno sobre o investimento.

- **Negociação de Contratos:** Considerar a possibilidade de renegociar contratos com as empresas que receberam valores elevados para buscar melhores condições financeiras ou serviços adicionais que possam agregar mais valor à licitação.

- **Diversificação de Fornecedores:** Avaliar a possibilidade de diversificar os fornecedores para reduzir a dependência de uma única empresa, especialmente aquelas que recebem os maiores montantes.

- **Revisão de Critérios de Seleção:** Rever os critérios de seleção utilizados na licitação para garantir que estão promovendo uma competição justa e selecionando os fornecedores mais adequados com base em critérios objetivos.

- **Transparência e Prestação de Contas:** Manter um alto padrão de transparência na gestão dos recursos públicos, garantindo que todas as decisões e alocações sejam bem documentadas e justificadas.


# Resultado "ótimo": 

In [41]:
licitacao['Mínimo'] = licitacao.drop(['Item','Descrição do Item','Quantidade'],axis=1).min(axis=1)
display(licitacao)

minimo = licitacao['Mínimo'].sum()
print(minimo)


Item Descrição do Item  Quantidade  Empresa A  Empresa B  Empresa C  \
0       1            Item 1          50       2350       1250       1450   
1       2            Item 2          96       2688       1632       2496   
2       3            Item 3          58       1566        754       1276   
3       4            Item 4          69       1863        828       3450   
4       5            Item 5          61       1342       1281       1708   
..    ...               ...         ...        ...        ...        ...   
195   196          Item 196          60       1440       1440       1020   
196   197          Item 197          82       2050       1066       3116   
197   198          Item 198         100       3400       2000       1100   
198   199          Item 199          67        804       1072       2680   
199   200          Item 200          59       1180       1357       1121   

     Empresa D  Empresa E  Empresa F  Empresa G  Empresa H  Mínimo  
0         2100       2050       1000        650       2450     650  
1         2208       1248       2592       1440       1056    1056  
2         1914       1508       2146       2378       1508     754  
3          759       1932       2208       1725       3105     759  
4         1769       2684       1830       2318        610     610  
..         ...        ...        ...        ...        ...     ...  
195       2400       1620       2100       2160       2580    1020  
196       1886       1394       3608       3608       1804    1066  
197       1000       3300       4900       1100       1100    1000  
198       1809       2814       2881        670       3015     670  
199       1357       1711       2419       2065        767     767  

[200 rows x 12 columns]

193299


# Criando uma planilha de desvios por fornecedor:

In [44]:
for empresa in licitacao.columns[3:-1]:
    desvio = licitacao [['Item','Descrição do Item','Quantidade', 'Empresa A', 'Mínimo']]
    desvio['Delta'] = desvio['Empresa A'] - desvio['Mínimo']
    desvio.to_excel('Desvio - ' + empresa + '.xlsx', index = False)

C:\Users\Lize\AppData\Local\Temp\ipykernel_14916\1399349270.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  desvio['Delta'] = desvio['Empresa A'] - desvio['Mínimo']
C:\Users\Lize\AppData\Local\Temp\ipykernel_14916\1399349270.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  desvio['Delta'] = desvio['Empresa A'] - desvio['Mínimo']
C:\Users\Lize\AppData\Local\Temp\ipykernel_14916\1399349270.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[r